INSERT INTO message(message_cd,message_typ,message_nm,created_at,updated_at,del_flg) VALUES (1,'4',N'Incorrect username or password..',NULL,NULL,0)
INSERT INTO message(message_cd,message_typ,message_nm,created_at,updated_at,del_flg) VALUES (2,'4',N'You do not have permission to log in.',NULL,NULL,0)
INSERT INTO message(message_cd,message_typ,message_nm,created_at,updated_at,del_flg) VALUES (3,'4',N'This field cannot be empty.',NULL,NULL,0)
INSERT INTO message(message_cd,message_typ,message_nm,created_at,updated_at,del_flg) VALUES (4,'4',N'Invalid email address.',NULL,NULL,0)
INSERT INTO message(message_cd,message_typ,message_nm,created_at,updated_at,del_flg) VALUES (5,'1',N'Saved successfully.',NULL,NULL,0)
INSERT INTO message(message_cd,message_typ,message_nm,created_at,updated_at,del_flg) VALUES (6,'1',N'Password confirmation does not match.',NULL,NULL,0)
INSERT INTO message(message_cd,message_typ,message_nm,created_at,updated_at,del_flg) VALUES (7,'1',N'This field must be unique.',NULL,NULL,0)
INSERT INTO message(message_cd,message_typ,message_nm,created_at,updated_at,del_flg) VALUES (8,'1',N'This field does not exist.',NULL,NULL,0)
